feat: adding github labeler
target/sensu-go-goalert pull request #5
Opened 2023-04-10 16:59 UTC by AlaricWhitney

adding github PR size labeler

2023-04-12 14:29 UTC, Forfold approved these changes, later dismissed

2023-04-14 16:45 UTC, mastercactapus requested changes

2023-04-14 16:45 UTC, mastercactapus commented on .github/workflows/labeler.yml
> +            "migrate/schema.sql"
let's clean this up since it's not the GoAlert repo

2023-04-26 15:36 UTC, Forfold approved these changes

2023-04-26 17:16 UTC, merged